# Load libraries

In [1]:
import pandas as pd

# Read cleaned files

In [2]:
data = pd.read_csv('../data/clean/stores_cleaned.csv')
data.head()

,Unnamed: 0,store_id,country,city,store_name,number_of_employees,zip_code,latitude,longitude
0,0,1,United States,New York,Store New York,10,10001,40.7128,-74.0060
1,1,2,United States,Los Angeles,Store Los Angeles,8,90001,34.0522,-118.2437
2,2,3,United States,Chicago,Store Chicago,9,60601,41.8781,-87.6298
3,3,4,United States,Houston,Store Houston,10,77001,29.7604,-95.3698
4,4,5,United States,Phoenix,Store Phoenix,9,85001,33.4484,-112.0740

## Tables without foreign keys

### Countries

In [7]:
countries = pd.DataFrame({"country_id": [i+1 for i in range(data['country'].nunique())], "country": [value if value != '中国' else 'China' for value in data['country'].unique()]})
countries

   country_id         country
0           1   United States
1           2           China
2           3     Deutschland
3           4  United Kingdom
4           5          France
5           6          España
6           7        Portugal

In [9]:
countries.to_csv("../data/clean/countries.csv", index=False, sep=";", encoding="utf-8")

### Payment methods

In [10]:
data = pd.read_csv('../data/clean/transactions_cleaned.csv')
data.head()

,Unnamed: 0,invoice_id,line,customer_id,product_id,size,color,unit_price,quantity,date,...,employee_id,currency,currency_symbol,sku,transaction_type,payment_method,invoice_total,Month,Year,Day
0,0,INV-US-001-03558761,1,47162,485,M,NaN,80.5,1,2023-01-01 15:42:00,...,7,USD,$,MASU485-M-,Sale,Cash,126.7,1,2023,6
1,1,INV-US-001-03558761,2,47162,2779,G,NaN,31.5,1,2023-01-01 15:42:00,...,7,USD,$,CHCO2779-G-,Sale,Cash,126.7,1,2023,6
2,2,INV-US-001-03558761,3,47162,64,M,NEUTRAL,45.5,1,2023-01-01 15:42:00,...,7,USD,$,MACO64-M-NEUTRAL,Sale,Cash,126.7,1,2023,6
3,3,INV-US-001-03558762,1,10142,131,M,BLUE,70.0,1,2023-01-01 20:04:00,...,6,USD,$,FECO131-M-BLUE,Sale,Cash,77.0,1,2023,6
4,4,INV-US-001-03558762,2,10142,716,L,WHITE,26.0,1,2023-01-01 20:04:00,...,6,USD,$,MAT-716-L-WHITE,Sale,Cash,77.0,1,2023,6

In [14]:
#create dictionary for id key and name
# with list comprehension check nunique()

payment_methods = pd.DataFrame({"payment_method_id": [i+1 for i in range(data['payment_method'].nunique())], "payment_method": [value for value in data['payment_method'].unique()]})
payment_methods

   payment_method_id payment_method
0                  1           Cash
1                  2    Credit Card

In [15]:
payment_methods.to_csv("../data/clean/payment_methods.csv", index=False, sep=";", encoding="utf-8")